services:
  backend:
    build:
      context: ./backend 
    container_name: backend
    volumes:
      - ./backend:/var/www/html 
      - sqlite_data:/var/www/html/database 
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - APP_URL=http://localhost:8000
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "php artisan storage:link &&
             chown -R www-data:www-data storage &&
             chmod -R 775 storage &&
             php artisan serve --host=0.0.0.0 --port=8000"
    working_dir: /var/www/html
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist/agendamento-acolhidos:/usr/share/nginx/html 
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - API_URL=http://backend:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local

