services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
      - /home/marcos/Vídeos/hostel-system-Tcc/backend/database/database.sqlite:/var/www/html/database/database.sqlite:rw
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - APP_URL=http://localhost:8000
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "php artisan storage:link &&
            chown -R www-data:www-data storage &&
            chmod -R 775 storage &&
            php artisan serve --host=0.0.0.0 --port=8000"
    working_dir: /var/www/html
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      # Mapeia o diretório 'dist/agendamento-acolhidos' do seu host
      # para o diretório de serviço do Nginx dentro do contêiner.
      # Certifique-se de que 'agendamento-acolhidos' é o nome da subpasta gerada pelo 'ng build'.
      - ./frontend/dist/hostel-system-Tcc:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - API_URL=http://backend:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    name: app-network
    driver: bridge
